--------------------------------------------------------
--  DDL for Table BTCUSD_ERR$
--------------------------------------------------------

  CREATE TABLE "BTCUSD_ERR$" 
   (	"ORA_ERR_NUMBER$" NUMBER, 
	"ORA_ERR_MESG$" VARCHAR2(2000 BYTE), 
	"ORA_ERR_ROWID$" UROWID (4000), 
	"ORA_ERR_OPTYP$" VARCHAR2(2 BYTE), 
	"ORA_ERR_TAG$" VARCHAR2(2000 BYTE), 
	"ID" VARCHAR2(4000 BYTE), 
	"DATE_" VARCHAR2(4000 BYTE), 
	"OPEN" VARCHAR2(4000 BYTE), 
	"HIGH" VARCHAR2(4000 BYTE), 
	"LOW" VARCHAR2(4000 BYTE), 
	"CLOSE" VARCHAR2(4000 BYTE), 
	"VOLUME__BTC_" VARCHAR2(4000 BYTE), 
	"VOLUME__CURRENCY_" VARCHAR2(4000 BYTE), 
	"WEIGHTED_PRICE" VARCHAR2(4000 BYTE)
   ) ;

   COMMENT ON TABLE "BTCUSD_ERR$"  IS 'DML Error Logging table for "BTCUSD"';
