--------------------------------------------------------
--  DDL for Table EBA_DEMO_CHART_STOCKS
--------------------------------------------------------

  CREATE TABLE "EBA_DEMO_CHART_STOCKS" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"STOCK_CODE" VARCHAR2(4 BYTE), 
	"STOCK_NAME" VARCHAR2(130 BYTE), 
	"PRICING_DATE" DATE, 
	"PRICING_TIMESTAMP" TIMESTAMP (6), 
	"PRICING_TIMESTAMP_TZ" TIMESTAMP (6) WITH TIME ZONE, 
	"OPENING_VAL" NUMBER, 
	"HIGH" NUMBER, 
	"LOW" NUMBER, 
	"CLOSING_VAL" NUMBER, 
	"VOLUME" NUMBER, 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) ;
