--------------------------------------------------------
--  DDL for Table EBA_DEMO_CHART_TASKS
--------------------------------------------------------

  CREATE TABLE "EBA_DEMO_CHART_TASKS" 
   (	"ID" NUMBER, 
	"PROJECT" NUMBER, 
	"PARENT_TASK" NUMBER, 
	"TASK_NAME" VARCHAR2(255 BYTE), 
	"ROW_VERSION_NUMBER" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(30 BYTE), 
	"ASSIGNED_TO" VARCHAR2(30 BYTE), 
	"COST" NUMBER, 
	"BUDGET" NUMBER, 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) ;
