REM INSERTING into EBA_DEMO_CHART_GRADES
SET DEFINE OFF;
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (1,'English',93,53,71,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2,'Physics',61,55,65,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (3,'English',70,50,90,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (4,'Math',50,70,45,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (5,'English',30,67,90,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (6,'English',85,56,67,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (7,'Math',70,45,59,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (8,'Math',62,53,66,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (9,'English',77,50,60,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (10,'English',90,54,69,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (11,'Physics',60,40,64,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (12,'English',88,28,67,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (13,'Math',71,56,45,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (14,'Math',63,58,64,null,null,null,null);
Insert into EBA_DEMO_CHART_GRADES (ID,COURSE,SCHOOLA,SCHOOLB,SCHOOLC,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (15,'English',59,54,65,null,null,null,null);
