REM INSERTING into EBA_DEMO_CHART_SAMPLE_NAMES
SET DEFINE OFF;
Insert into EBA_DEMO_CHART_SAMPLE_NAMES (ID,SAMPLE_NAME,SAMPLE_DATE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (1,'Sample 1',to_date('20/JUL/17','DD/MON/RR'),null,null,null,null);
Insert into EBA_DEMO_CHART_SAMPLE_NAMES (ID,SAMPLE_NAME,SAMPLE_DATE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2,'Sample 2',to_date('27/JUL/17','DD/MON/RR'),null,null,null,null);
Insert into EBA_DEMO_CHART_SAMPLE_NAMES (ID,SAMPLE_NAME,SAMPLE_DATE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (3,'Sample 3',to_date('30/JUL/17','DD/MON/RR'),null,null,null,null);
Insert into EBA_DEMO_CHART_SAMPLE_NAMES (ID,SAMPLE_NAME,SAMPLE_DATE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (4,'Sample 4',to_date('03/AUG/17','DD/MON/RR'),null,null,null,null);
Insert into EBA_DEMO_CHART_SAMPLE_NAMES (ID,SAMPLE_NAME,SAMPLE_DATE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (5,'Sample 5',to_date('10/AUG/17','DD/MON/RR'),null,null,null,null);
